services:
  mongo:
    image: mongo:7
    hostname: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - mongodb-data:/data/db
    labels:
      - "traefik.enable=false"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  postgres:
    image: postgres:16-alpine
    hostname: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  redis:
    image: redis:7
    hostname: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - redis-data:/data
    labels:
      - "traefik.enable=false"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  mosquitto:
    image: eclipse-mosquitto:2
    hostname: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/passwordfile:/mosquitto/config/passwordfile
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  rabbitmq:
    build: ./rabbitmq
    hostname: rabbitmq
    networks:
      traefik:
    ports:
      - "1884:1884"
      - "5672:5672"
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    labels:
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.fernandoglatz.com`)"
      - "traefik.http.routers.rabbitmq.service=rabbitmq"
      - "traefik.http.routers.rabbitmq.middlewares=oauth"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
      - "traefik.docker.network=traefik"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

volumes:
  mongodb-data:
  mosquitto-data:
  mosquitto-log:
  postgres-data:
  rabbitmq-data:
  redis-data:

networks:
  traefik:
    name: traefik
    external: true
